// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvT3Bxu3AnpKxNsIqtVz1te4YR-CSYFfY',
    appId: '1:58778947096:web:a3092ea3011dc40568fd6d',
    messagingSenderId: '58778947096',
    projectId: 'ecommerc-50b6f',
    authDomain: 'ecommerc-50b6f.firebaseapp.com',
    storageBucket: 'ecommerc-50b6f.appspot.com',
    measurementId: 'G-FDCTMVEMRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkO3LiAHWe6PPO-jyQAGy9ycr28_0S_A',
    appId: '1:58778947096:android:e7007b0536d8281f68fd6d',
    messagingSenderId: '58778947096',
    projectId: 'ecommerc-50b6f',
    storageBucket: 'ecommerc-50b6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb4Lr39nlqMdXtleDtXYHqkAiuGes2hZQ',
    appId: '1:58778947096:ios:380b13258ae9de4368fd6d',
    messagingSenderId: '58778947096',
    projectId: 'ecommerc-50b6f',
    storageBucket: 'ecommerc-50b6f.appspot.com',
    iosBundleId: 'com.example.ecommercApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb4Lr39nlqMdXtleDtXYHqkAiuGes2hZQ',
    appId: '1:58778947096:ios:0cd1bd5bcdd2bc4e68fd6d',
    messagingSenderId: '58778947096',
    projectId: 'ecommerc-50b6f',
    storageBucket: 'ecommerc-50b6f.appspot.com',
    iosBundleId: 'com.example.ecommercApp2.RunnerTests',
  );
}
